push_path="~/rsh-remote"
version=v0.0.0.91
db_items="bindgen.conf bindgen.sh CHANGELOG CONTRIBUTING custom-http docs/argshift docs/bail docs/clearvars docs/confedit docs/config docs/grab docs/init docs/plugins docs/pull docs/push docs/README docs/revision example.conf FEATURES index.html LICENSE README rsh.sh sh-caveats src/argshift src/bail src/cl src/clearvars src/confedit src/config src/confload src/confload_l1 src/db src/db_build src/debug src/grab src/help src/init src/main src/ops src/prePush src/pull src/push src/revi src/shcat src/vfunc standalone.sh .rsh.conf"
remote_url="https://r.transcendent.ink/rsh"
repo_name=rsh
push_ready=
