#!/bin/sh
orgfunc=revi
printf '%s' "${DEBUG+!! COMMIT w/ \"$@\"$nl}"
hook revi pre
# revision func
if [ ! "$revi_replace" ]; then
  [ ! "$push_ready" ] && {
    [ "$version" -o "$1" ] && {
      printf '%s' "${DEBUG+!! INCREMENT VERSION CODE$nl}"
      # expected syntax is v0.0.0.0
      # however v1, v0.01.0, v0.0.01.0, etc are all still valid
      # force the current version code into the expected syntax, then increment
      version="${version#${version_prefix:-v}}"
      # 000.000.000.000
      case "$1" in
        ("release") incr="1000000000";; # 001.000.000.000
        ("alpha") incr="1000";; # 000.000.001.000
        ("beta") incr="1000000";; # 000.001.000.000
        ("dev") incr="1";; # 000.000.000.001
        (""|"auto") incr="1";; # treat auto as dev unless at dev limit
        ("custom") version="$2"; incr="";;
      esac
      # remove prefix
      ###
      # Design
      # -- this is designed in a simplistic fashion
      # ---- idea is to take advantage version codes
      # ---- v0.0.0.0
      #      Release - Features Fully implemented
      #              -- Major Feature release
      #      Beta    - Mostly Implemented
      #              -- features release candidate features
      #              -- betas can be used as a pre-release
      #              -- useful for minor features or parts of major features
      #      Alpha   - Barely Functioning; possibly with bugs
      #              -- features experimental features
      #              -- likely still under review and maintenance
      #      dev     - extreme dev; simply used for remote saves
      #              -- do not use dev commits in production or personal use
      #              -- they exist only for dev actively working on the code
      #              -- and are not intended to form a working product;
      #              ---- a simpler form of "master"
      ##
      # Basically you can take advantage of this by removing the separators, then
      # treating it like a regular number; after expanding the version code to the full
      # v000.000.000.000
      ###
      printf '%s' "${DEBUG+!! INCREMENT VERSION FROM $version$nl}"
      [ "$incr" ] && {
        version=$(vfunc "$version")
        until [ "${version#0}" = "$version" ]; do
          version="${version#0}"
        done
        version=$((version+incr))
        version=$(vfunc "$version" _)
      }
      printf '%s' "${DEBUG+!! VERSION BECAME $version$nl}"
      confedit "./${config_hidden}rsh.conf" version="v${version#${version_prefix:-v}}"
      printf '%s' "${DEBUG+!! PREPARE FOR PUSH$nl}"
      prePush
    } || {
      printf '%s' "${DEBUG+!! FIRST VERSION$nl}"
      confedit "./${config_hidden}rsh.conf" version="v0.0.0.1"
      printf '%s' "${DEBUG+!! SETUP PUSH$nl}"
      # this is equal to v0.0.0.001 & v000.000.000.001
      prePush
    }
  } || {
    # shellcheck disable=SC2016
    bail '$push_ready IS SET; UNSET TO CONTINUE' "revi() will not operate unless you unset push_ready"
  }
  # revi should not operate if push_ready is set
else 
  ${revi_replace}
fi
printf '%s\n' "-- Committed. New version is $version. Ready for Push."
hook revi post
